### ISSUE TITLE
Improve recipe file structure

### ISSUE THREAD

**Issue by spflueger** [ComPWA/expertsystem#73]
- [x] Add Magnitude and Phase as individual Parameters instead of defining a Type inside Parameter
This will remove some overhead and the code will still be flexible enough. So the content of Magnitude and Phase will just follow Parameter.
- [x] Simplify `DecayProducts`
```yml
DecayParticle:
  Name: J/psi
  Helicity: -1
DecayProducts:
  - Name: f2(1950)
    FinalState: [3, 4]
    Helicity: 0.0
  - Name: gamma
    FinalState: 2
    Helicity: -1
```
- [ ] Refer to object directly instead of `Class` tags
```yml
NormalizedIntensity:
  IncoherentIntensity:
      - CoherentIntensity:
        Component: coherent_J/psi_-1_to_gamma_-1+pi0_0+pi0_0
        Amplitudes:
          CoefficientAmplitude:
            Component: J/psi_-1_to_f2(1270)_0+gamma_-1;f2(1270)_0_to_pi0_0+pi0_0;
            Parameters:
              Magnitude: *par1
              Phase: *par2
            SequentialAmplitude:
                - HelicityDecay:
```

**[Estimated effort: 2h]**

**Comment by redeboer** [comment]
> Add Magnitude and Phase as individual Parameters instead of defining a Type inside Parameter. This will remove some overhead and the code will still be flexible enough. So the content of Magnitude and Phase will just follow Parameter.

Is that the case now since v0.1.2a0? Or do you mean something else?

**Comment by redeboer** [comment]
> Refer to object directly instead of `Class` tags

The syntax from `CoherentIntensity:` on is invalid YAML syntax. That's why we need a `Class` tag.

**Comment by spflueger** [comment]
> > Refer to object directly instead of `Class` tags
> 
> The syntax from `CoherentIntensity:` on is invalid YAML syntax. That's why we need a `Class` tag.

How so?

**Comment by spflueger** [comment]
> > Add Magnitude and Phase as individual Parameters instead of defining a Type inside Parameter. This will remove some overhead and the code will still be flexible enough. So the content of Magnitude and Phase will just follow Parameter.
> 
> Is that the case now since [0.1.2a0](https://github.com/ComPWA/expertsystem/releases/tag/0.1.2-alpha)? Or do you mean something else?

Yeah this part is already solved. We could remove the `Parameters` tag inside Amplitudes, so instead of writing
```
Parameters:
  Magnitude: Magnitude_J/psi_to_f2(1270)_2+gamma_1;f2(1270)_to_pi0_0+pi0_0;
  Phase: Phase_J/psi_to_f2(1270)_2+gamma_1;f2(1270)_to_pi0_0+pi0_0;
```
we could just write
```
Magnitude: Magnitude_J/psi_to_f2(1270)_2+gamma_1;f2(1270)_to_pi0_0+pi0_0;
Phase: Phase_J/psi_to_f2(1270)_2+gamma_1;f2(1270)_to_pi0_0+pi0_0;
```

**Comment by redeboer** [comment]
```yaml
      - CoherentIntensity:
        Component: coherent_J/psi_-1_to_gamma_-1+pi0_0+pi0_0
        Amplitudes:
```
Either requires indentation before `Component:` and `Amplitudes:` or `Class: CoherentIntensity`.
